class ValidExcept(Exception):

    def __str__(self):
        return "The valid error has been occurred"
